### ISSUE TITLE
Misleading error message when using access keys of the wrong type

### ISSUE THREAD

**Issue by kek** [erlcloud/erlcloud#155]
When using character lists instead of strings for the AWS credentials, a timeout error is generated.

```
11> erlcloud_s3:configure('a', 'b').
ok
12> erlcloud_s3:list_buckets().
** exception error: {aws_error,{socket_error,timeout}}
     in function  erlcloud_s3:s3_request/8 (src/erlcloud_s3.erl, line 971)
     in call from erlcloud_s3:s3_xml_request/8 (src/erlcloud_s3.erl, line 955)
     in call from erlcloud_s3:list_buckets/1 (src/erlcloud_s3.erl, line 296)
13> 
```

**Comment by motobob** [comment]
true. 
`configure` functions of all module should not allow anything except lists. 
A PR with fixes as simple as adding guards is welcome.

**Comment by paulo-ferraz-oliveira** [comment]
If dialyzed (e.g. `rebar3 dialyzer`) this issue is apparent as "lib. consumer is doing something wrong here": `The call erlcloud_s3:configure('a', 'b') will never return since the success typing is (string(), string()) -> 'ok' and the contract is (string(), string()) -> 'ok'`.

@motobob, do you still feel a PR would be useful to "fix" this wrong use of the lib.?
