### ISSUE TITLE
Authorization being in process dictionary is unexpected / unintuitive

### ISSUE THREAD

**Issue by jacobgreenleaf** [erlcloud/erlcloud#204]
`erlcloud_s3:configure(X, Y)` configures the `erlcloud_s3` module to use access key X, but only for the caller, since it uses the process dictionary. This is unexpected; other libraries such as `httpc` that have default configuration usually do such configuration for all callers. 

Using `os:putenv` is an _okay_ workaround, but it would be great if it had an API similar to `httpc`, preferably using built-in `application:get_env`.

**Comment by ransomr** [comment]
I agree this is an issue and I think using application environment would be an improvement. I'd be open to a PR that does that as long as it wouldn't break current clients. As I work-around I just pass the config explicitly into all ercloud methods.

**Comment by jacobgreenleaf** [comment]
Unfortunately there is an issue with uploading large files that causes a crash because the node runs out of memory. I think it is related to the way the worker gen_server handles the binaries it gets from reading each piece of the file. I'm keeping this PR open for overall review but don't advise merging.

**Comment by motobob** [comment]
@jacobgreenleaf there are uses cases when even `application:set_env/get_env` is not *okay*. Imagine a common situation with a server running `erlcloud` pointed to several different AWS accounts and regions. 
Passing different `#aws_config{}` records to the calling API is not just a work-around but a preferable option, IMO. That's why these API funs exist in every module.

Let's me know if you question has been answered and if I can close the issue

**Comment by ondevsergeyl** [comment]
I'm worry about this issue also. I think config should be passed via arguments of functions. It is best way.

It is not good, when we can have garbage in process dictionary (PD). 

What happens if i will have 1M processes and will call s3-functions within each process. It means i will have 1M records inside PD. As minimum i should be able to delete this config from PD and this opportunity should be provided by this library.

Thanks.

**Comment by loguntsov** [comment]
I'm worry about this issue also. I think config should be passed via arguments of functions. It is best way.

It is not good, when we can have garbage in process dictionary (PD).

What happens if i will have 1M processes and will call s3-functions within each process. It means i will have 1M records inside PD. As minimum i should be able to delete this config from PD and this opportunity should be provided by this library.

Thanks.

**Comment by motobob** [comment]
@ondevsergeyl almost all API functions in all modules allow you to pass `#Aws_config{}` records and there is no requirement to use configure API at. that exists solely for the use case when the library is deployed in an application sharing a single identity. 
this is widely used in our code where we operate with thousands of different configs for different AWS accounts. 
hope that's covered. let me know if any more questions.

**Comment by loguntsov** [comment]
But you should give us way to clean PD. Yes ? 
if you have this function, can you show me this code ?

**Comment by motobob** [comment]
there is no function to clean PD, at least i'm not aware of such. that should probably be added

**Comment by alexturkin** [comment]
I suggest to:

* declare all current `module:configure` functions as deprecated
* stop adding it in the new modules

@motobob @ransomr @nalundgaard what do you guys think?
