### ISSUE TITLE
Update meck dependency

### ISSUE THREAD

**Issue by webzepter** [erlcloud/erlcloud#260]
It seems [meck](https://github.com/eproxus/meck/releases) dependency is outdated. Please, update it! :pray:

**Comment by motobob** [comment]
it used to be meck/master and 0.8.4 specifically and afterward it was downgraded to 0.8.3 by https://github.com/erlcloud/erlcloud/pull/228.

is the request to update to 0.8.4?

**Comment by webzepter** [comment]
@motobob yes

**Comment by motobob** [comment]
please explain why this is necessary. 
as it's minor version difference and I also do not see major changes https://github.com/eproxus/meck/compare/0.8.3...0.8.4

if you really need 0.8.4 in your project because of other components i would encourage pinning meck to 0.8.4 above erlcloud in rebar.config file.

**Comment by webzepter** [comment]
Our project is covered by tests written with [Espec](https://github.com/antonmi/espec), but latest versions of `espec` [depend](https://github.com/antonmi/espec/blob/master/mix.exs#L25) on `meck` 0.8.4

**Comment by smilerlee** [comment]
thanks @webzepter and @motobob
