### ISSUE TITLE
does anybody here use SimpleDB?

### ISSUE THREAD

**Issue by motobob** [erlcloud/erlcloud#361]
Hello all,

currently, i'm in the process of cleaning up SigV4 support in the library where there are multiple implementations and thus several bugs. I would like to have one clean in `erlcloud_aws` which all the other module use. 
The only service which is no SigV4 and is still on SigV2 is SimpleDB. http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html.
The service is also available in limited number of [relatively old regions](http://docs.aws.amazon.com/general/latest/gr/rande.html#sdb_region). 
It does not seem AWS is going to evolve the service any further as i'm unaware of any features added over the year to it. 
Also, (yuno) DDB.
https://aws.amazon.com/dynamodb/faqs/#How_does_Amazon_DynamoDB_differ_from_Amazon_SimpleDB_Which_should_I_use and further http://www.allthingsdistributed.com/2012/01/amazon-dynamodb.html

So, I would like to remove SigV2 completely which means `erlcloud_sdb` will disappear too.
That will be performed as part of major rev bump together with the rest of non-backward compatible changes planned at the moment. 

I'll keep this open for 2 weeks to give a chance to voice concerns if any.

**Comment by motobob** [comment]
@ptrakhtman @nalundgaard any input on this?

**Comment by nalundgaard** [comment]
Would it be horrifying to move the code that SDB relies on exclusively into its module, so that it is no longer shared by the common (SigV4) request code of the rest of the modules?

If it's just a copy-paste of the existing code into the erlcloud_sdb module that can then be left there and not worried about anymore, I don't see the harm in doing that to avoid undue pain for anyone using the library. We could also formally deprecate the module (via xref and/or @deprecated edoc) in so doing.

It's extra overhead, but it sounds more responsible to clients to me.

**Comment by motobob** [comment]
okay, i'm willing to take that overhead but however i still see very little value in it.
probably i'll mark it as `@deprecated` and we will remove it in future.

**Comment by motobob** [comment]
closing the question as feedback received. 
PR is coming soon.
