### ISSUE TITLE
Cannot use filters in erlcloud_ec2:describe_instances/4

### ISSUE THREAD

**Issue by jvdvleuten** [erlcloud/erlcloud#370]
The function clause inhibits use of the filter function.

`erlcloud_ec2:describe_instances([{"tag:Cluster", ["clustername"]}], undefined, undefined, Config).`

results in a `function_clause` error.

When setting the `MaxResults` to 5 (the minimum) I get an AWS EC2 error:

`{error,{http_error,400,"Bad Request", <<"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter 'maxResults' cannot be used with tag filters in the parameter 'filterSet'. Remove either the tag filters from 'filterSet' or the 'maxResults' parameter and try again.</Message></Error></Errors><RequestID>6d578aa5-ebd2-4a09-8b25-e27c505e87fd</RequestID></Response>">>}}`

I can fix this by adding expanding the guard clause to this, to allow a filter with an undefined MaxResults:

```
describe_instances(Filter, MaxResults, NextToken, Config)
    when is_list(Filter) orelse Filter =:= none,
         is_integer(MaxResults) andalso MaxResults >= ?INSTANCES_MR_MIN andalso MaxResults =< ?INSTANCES_MR_MAX orelse Filter =/= none andalso MaxResults =:= undefined,
         is_list(NextToken) orelse NextToken =:= undefined,
         is_record(Config, aws_config) ->
```

I will try and make a pull request.

**Comment by motobob** [comment]
@jvanvleet I do not think the PR is correct for you given purpose.

did you try using the following if you need only filters?
```erlang
erlcloud_ec2:describe_instances([], [{"tag:Cluster", ["clustername"]}], Config).
```

wrt describe_instances/4 with both filter and max_results you investigation is correct and that should be fixed.
@SergeyOvchinnik please address this and check other describe_* funs for same symptoms.

**Comment by SergeyOvchinnik** [comment]
Hi, @jvdvleuten 

This clause is for paginated calls only, so I made it so that `MaxResults` has to be specified here. If you are not specifying it, there is no reason to use the paginated clause anyway.

As for tag filters, AWS API does not allow using pagination together with tag filters, as stated in `http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html`. All other filters still work with pagination though.

As @motobob mentioned, you can use just `Filters` and `Config` in `describe_instances/3` by using `[]` value for `InstanceIDs` param.

**Comment by motobob** [comment]
please re-open if describe_instances/3 does not work for you

**Comment by jvdvleuten** [comment]
Perfect, thank you. Maybe something for the docs that you are supposed to provide `[]` value for `InstanceIDs`?
