### ISSUE TITLE
 Upcoming Changes to SSL Certificates in Amazon DynamoDB

### ISSUE THREAD

**Issue by nicolasmd87** [erlcloud/erlcloud#490]
I'v received this in a mail from Amazon while using the latest version of erlcloud:

"We recently analyzed your use of DynamoDB. During that process, we noticed you have a system that makes calls to DynamoDB using either an older AWS SDK or an unknown SDK that may not support SSL/TLS certificates issued by Amazon Trust Services (ATS)."

**Comment by nalundgaard** [comment]
erlcloud is definitely an "unknown SDK." Whether it supports ATS-issued certificates is a function of how you build your Erlang VM rather than erlcloud itself. There's more here:

https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/

Also, I think by default, lhttpc does not verify peer SSL certificates. I believe you have to configure a cacert file to pass into the httpc options when doing this, and it does not appear to be done in the code.

**Comment by motobob** [comment]
@nicolasmd87 yes. This is true and we are aware. The move to ATS is not cheap. Especial for old erlangs and etc. 
We will run through the same process here soon. 

As @nalundgaard mentioned this has nothing to do with `erlcloud` itself and is more about ErlVm or Elixir build of your application. 
Please let us know what is the expectation on this issue from your side. 

Example of how to reproduce the issue where a version of Erlang X of latest ercloud Y cannot establish a connection to AWS will be helpful.

**Comment by fogfish** [comment]
A similar impact on my side as well. We might need to tune how the https requests are issued. Let me know if any help is need on this issue.

**Comment by motobob** [comment]
so, current erlcloud/lhttpC does not even validate certs here so this should be no-op. 
our stuff runs R19+ and has no issues atm. 

@fogfish do you expect any changes at all?

**Comment by fogfish** [comment]
Just testing it. I am running on 20+ No issues yet.

**Comment by motobob** [comment]
everybody survived... all good. 
I see no point in keeping this open. Feel fre to re-open. 

if there are instalments where this is an issue tuning to lhttpC but not erlcloud are necessary
