### ISSUE TITLE
Options disregarded during delete_all operation

### ISSUE THREAD

**Issue by daniel-greening** [erlcloud/erlcloud#523]
When using the [erlcloud_ddb_utils:delete_all/4](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_ddb_util.erl#L98) function, options are disregarded during the batch write operation [here](https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_ddb_util.erl#L454). 

Is there a reason for ignoring this? Utilising the argument in this function would allow for the reporting of consumed capacity among other things.

**Comment by nalundgaard** [comment]
It doesn't do that because it makes (potentially) multiple requests, and there's no clear way to determine what the response would be. If you need that feature, you should use erlcloud_ddb2:batch_write yourself.

**Comment by motobob** [comment]
I might be missing smth but it's quite easy to enhance delete_all/4 to do this. it's very close to scan_all implementation here. if the same options are used for all sub-requests (which is the only valid approach) it's actually easy to sum that up.

currently it returns `ok|{error, term()}` so you might still want to create a new fun based on batch_write to not break previous apis.  If you could PR this it would be great.

**Comment by nalundgaard** [comment]
@motobob For what it's worth, `erlcloud_ddb_util:scan_all/3` has no support for returning ConsumedCapacity which the DynamoDB Scan API [does support](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html#DDB-Scan-response-ConsumedCapacity). It simply has ad-hoc support for returning the count of items in the table instead of the items themselves, and its own custom option for returning typed/untyped item output. It only supports returning a raw result, not metadata.

Notionally, `delete_all/4` could support a metadata response, since there's no aggregated result to return as there is in `scan_all/3`. Something like `{ok, ConsumedCapacityWithFieldWiseSumAcrossAllResponses}` could be done, but it sounds like it's of questionable value. ConsumedCapacity is a [complex object](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html#DDB-BatchWriteItem-response-ConsumedCapacity) with multiple modes of response that could make it [a pain to sum](https://github.com/erlcloud/erlcloud/blob/b70efdcdbac1f8723ae920b1731d512dd8eb9618/include/erlcloud_ddb2.hrl#L101-L107). There's also the question of support for returning [ItemCollectionMetrics](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html#DDB-BatchWriteItem-response-ItemCollectionMetrics), which is also a [record](https://github.com/erlcloud/erlcloud/blob/b70efdcdbac1f8723ae920b1731d512dd8eb9618/include/erlcloud_ddb2.hrl#L109-L112) that can be returned, with a much less clear method for multi-request client side aggregation.

Moreover, if you ultimately encounter an error after some number of requests, you won't get the data (delete_all simply returns `{error, Reason}`. So, I reiterate: IMHO it's much smarter to take `erlcloud_ddb_util:delete_all/4` as a reference implementation, and insert your own hooks for reporting of consumed capacity per call to `batch_write_item`. The AWS API is built for such a purpose, and I don't think this use case fits very well here.

I'm open to being persuaded otherwise, but IMO I don't think the `scan_all/4` example is a good analogue to the question at hand.

**Comment by daniel-greening** [comment]
@nalundgaard Thanks for the detailed response! After failing over the weekend to come up with a clean method to aggregate responses across multiple requests I'm in agreement that it'll be better to just implement my own version of the function at this point. 

Happy to close this issue.

**Comment by motobob** [comment]
closing, but please feel to PR the proposed changes back if you find a good way on top of batch-write.
