### ISSUE TITLE
Hex package has empty requirements

### ISSUE THREAD

**Issue by skorobkov** [erlcloud/erlcloud#616]
Hex package (3.2.10) has empty requirements in hex_metadata.config. So rebar3 (3.11.1) doesn't download jsx, lhttpc, eini and base16 packages.

**Comment by nalundgaard** [comment]
Man, rebar3, why? Sorry about that. I will look into it.

**Comment by nalundgaard** [comment]
Sorry, this looks like it's because I published with rebar3_hex 2.5.0, nothing to do with rebar3 per se. I pinned it earlier this year due to an issue I had with it (see tsloughter/rebar3_hex#117). 

I have updated to rebar3_hex 6.8.0, and plublished [erlcloud 3.2.11](https://hex.pm/packages/erlcloud/3.2.11). Sorry about that.
