### ISSUE TITLE
DynamoDB queries fail because headers are binaries

### ISSUE THREAD

**Issue by onetamer** [erlcloud/erlcloud#710]
Repro steps: try to make a DynamoDB request with Erlang 22 or 23, for example:

```
erlcloud_ddb2:list_tables().
```

This will crash. It seems that `httpc` attempts to convert headers to lowercase, however the function `string:to_lower` doesn't work with binaries. So in order to fix this issue I simply changed the headers to strings (lists) as shown here:

[https://github.com/onetamer/erlcloud/commit/ba92f0c0af255d6a514bf9923f6903036d15d805](https://github.com/onetamer/erlcloud/commit/ba92f0c0af255d6a514bf9923f6903036d15d805)

**Comment by nalundgaard** [comment]
Erlcloud does not use the `httpc` module, it uses [`erlcloud/lhttpc`](https://github.com/erlcloud/lhttpc) (hackney is optional). As far as I can tell, `lhttpc` supports binary, atom, and string values for headers. Is it possible that you're using a different version of lhttpc because of some other repository in your rebar dependency tree?

If you could show

1. A trace of the exception
2. The output of `rebar3 tree -v` on your project

That would be very helpful in understanding the issue. I am not necessarily opposed to this change if you want to PR it, but I would definitely like to fully understand this issue. `string:to_lower()` does not support binaries in any older version of Erlang/OTP, and we use erlcloud on OTP 21 extensively without experiencing this issue, so I am certain something else is amiss here.

**Comment by onetamer** [comment]
Thank you @nalundgaard for your feedback. I ended up deleting my rebar.lock file and _build folder then rebuilding from scratch and the error is gone. So you're right that something else was the problem. I'm going to close this issue.

Unrelated: by the way if you happen to know how to silence some of the warnings when using rebar3 release, please let me know. I'm getting a lot of messages like `*WARNING* inets: Source code not found: inets.erl`

**Comment by motobob** [comment]
if you use relx, check that for local run you have PATH set right and for prod deploys you have `  {include_erts, true}`
alike:
```
{profiles,
 [
  {prod,
   [
    {relx, 
     [
      {include_erts, true},
      {dev_mode, false}
     ]}
   ]}
 ]}.
```
