### ISSUE TITLE
Add support for the transcription service

### ISSUE THREAD

**Issue by jamesaimonetti** [erlcloud/erlcloud#756]
https://docs.aws.amazon.com/transcribe/latest/APIReference/API_StartTranscriptionJob.html

Wanted to reach out and see if this is on the roadmap? We (2600Hz) are interested in sponsoring the work if so.

**Comment by motobob** [comment]
sadly, due to historical reasons only this library is not OpenApi based and new modules/APIs are added on the ad-hoc basis. PR is welcome.

alternatively I'd suggest to use https://github.com/aws-beam/aws-erlang/blob/master/src/aws_transcribe.erl  and "semi-official" `aws-erlang` library. 

cc @carlisom

**Comment by jamesaimonetti** [comment]
@motobob thanks, appreciate the response. Will check out `aws-erlang`, thanks for the pointer.
